use_frameworks!
install! 'cocoapods', :generate_multiple_pod_projects => true

target 'logio_Example' do
  pod 'CocoaLumberjack/Swift'
  pod 'LogIO', :path => '../'
#  pod 'LogIO-CocoaLumberjack', :path => '../LogIO-CocoaLumberjack/'

  target 'logio_Tests' do
    inherit! :search_paths

    
  end
end
