use_frameworks!

target 'logio_Example' do
  pod 'CocoaLumberjack/Swift'
  pod 'logio', :path => '../'
#  pod 'LogIO-CocoaLumberjack', :path => '../LogIO-CocoaLumberjack/'

  target 'logio_Tests' do
    inherit! :search_paths

    
  end
end
